name: Add New Profile
description: Template for creating a new profile.

body:
  - type: markdown
    attributes:
      value: |
        ## Add New Profile

        Use this template to create a new profile and ensure all necessary steps are completed.

  - type: input
    id: profile_name
    attributes:
      label: Profile Name
      description: Enter the name of the new profile.
    validations:
      required: true

  - type: checkboxes
    id: tasks
    attributes:
      label: Task Checklist
      options:
        - label: Add new profile as shorthand file (in /input/fsh)
        - label: Add example instance(s) and test profile - (Look at QA report /output/qa.html)
        - label: Add to resource reference summary /pagecontent/resourcereferencesummary.md
        - label: Check if it needs adding to /pagecontent/profiles-and-extensions.md
        - label: Add to Variance statement /pagecontent/variance.md
        - label: Update any mentions in the AUeReqDI Mappings page /pagecontent/auereqdi.md
        - label: Add any valuesets/codesystems and profiles where used to /pagecontent/terminology.md
        - label: Add to conformance for the 4 actors /resources/au-erequesting-filler.xml, /resources/au-erequesting-placer.xml, /resources/au-erequesting-server.xml, /resources/au-erequesting-patient.xml
        - label: Add search param examples and conformance table (see task_notes.md and task_parameters.md for examples)
        - label: Add new profile to /pagecontent/changes.md

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Add any additional notes or details about the new profile.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Creator Information

  - type: input
    id: creator_name
    attributes:
      label: Creator Name
    validations:
      required: true

  - type: input
    id: creation_date
    attributes:
      label: Creation Date
      placeholder: YYYY-MM-DD
    validations:
      required: true